// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Author documents
 */
interface AuthorDocumentData {
  /**
   * Name field in *Author*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Name of the author
   * - **API ID Path**: author.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Picture field in *Author*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author.picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;
}

/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AuthorDocumentData>,
    "author",
    Lang
  >;

type LandingPageDocumentDataSlicesSlice =
  | HeaderSlice
  | FaqSlice
  | SubheaderSlice
  | SpacerSlice
  | CtaSectionSlice
  | InfoSectionSlice
  | HowItWorksSlice;

/**
 * Content for Landing Page documents
 */
interface LandingPageDocumentData {
  /**
   * Page Title field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Landing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landing Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

type PostDocumentDataSlicesSlice = TextSlice | ImageSlice;

/**
 * Content for Post documents
 */
interface PostDocumentData {
  /**
   * Product name field in *Post*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Name of the product
   * - **API ID Path**: post.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Description field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description of the product
   * - **API ID Path**: post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Date field in *Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Date of publication
   * - **API ID Path**: post.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Author field in *Post*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: post.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<"author">;

  /**
   * Cover Image field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Price field in *Post*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Price in USD
   * - **API ID Path**: post.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;

  /**
   * Slice Zone field in *Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PostDocumentDataSlicesSlice>;
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PostDocumentData>, "post", Lang>;

export type AllDocumentTypes =
  | AuthorDocument
  | LandingPageDocument
  | PostDocument;

/**
 * Primary content in *CtaSection → Primary*
 */
export interface CtaSectionSliceDefaultPrimary {
  /**
   * Heading field in *CtaSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *CtaSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * CTA button text field in *CtaSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.primary.cta_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_button_text: prismic.KeyTextField;

  /**
   * Image field in *CtaSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Type field in *CtaSection → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.primary.type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<
    "Small" | "Medium" | "Large" | "withInfoRight" | "withInfoLeft"
  >;

  /**
   * IntroText field in *CtaSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Only for info slices
   * - **API ID Path**: cta_section.primary.introtext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  introtext: prismic.KeyTextField;

  /**
   * Info Title One field in *CtaSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.primary.info_title_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info_title_one: prismic.KeyTextField;

  /**
   * Info Subtitle One field in *CtaSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.primary.info_subtitle_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info_subtitle_one: prismic.KeyTextField;

  /**
   * Info Title Two field in *CtaSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.primary.info_title_two
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info_title_two: prismic.KeyTextField;

  /**
   * Info Subtitle Two field in *CtaSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.primary.info_subtitle_two
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info_subtitle_two: prismic.KeyTextField;

  /**
   * Info Title Three field in *CtaSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.primary.info_title_three
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info_title_three: prismic.KeyTextField;

  /**
   * Info Subtitle Three field in *CtaSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.primary.info_subtitle_three
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info_subtitle_three: prismic.KeyTextField;
}

/**
 * Default variation for CtaSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaSection*
 */
type CtaSectionSliceVariation = CtaSectionSliceDefault;

/**
 * CtaSection Shared Slice
 *
 * - **API ID**: `cta_section`
 * - **Description**: CtaSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSectionSlice = prismic.SharedSlice<
  "cta_section",
  CtaSectionSliceVariation
>;

/**
 * Primary content in *Faq → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Question field in *Faq → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *Faq → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.answer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer: prismic.KeyTextField;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Header → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * Title field in *Header → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Header → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * CTA button text field in *Header → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.primary.cta_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_button_text: prismic.KeyTextField;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Primary content in *HowItWorks → Primary*
 */
export interface HowItWorksSliceDefaultPrimary {
  /**
   * Step One Title field in *HowItWorks → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_it_works.primary.step_one_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_one_title: prismic.KeyTextField;

  /**
   * Step One Text field in *HowItWorks → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_it_works.primary.step_one_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_one_text: prismic.KeyTextField;

  /**
   * Step Two Title field in *HowItWorks → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_it_works.primary.step_two_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_two_title: prismic.KeyTextField;

  /**
   * Step Two Text field in *HowItWorks → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_it_works.primary.step_two_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_two_text: prismic.KeyTextField;

  /**
   * Step Three Title field in *HowItWorks → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_it_works.primary.step_three_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_three_title: prismic.KeyTextField;

  /**
   * Step Three Text field in *HowItWorks → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_it_works.primary.step_three_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_three_text: prismic.KeyTextField;
}

/**
 * Default variation for HowItWorks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HowItWorksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HowItWorksSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HowItWorks*
 */
type HowItWorksSliceVariation = HowItWorksSliceDefault;

/**
 * HowItWorks Shared Slice
 *
 * - **API ID**: `how_it_works`
 * - **Description**: HowItWorks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HowItWorksSlice = prismic.SharedSlice<
  "how_it_works",
  HowItWorksSliceVariation
>;

/**
 * Primary content in *Image → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *InfoSection → Primary*
 */
export interface InfoSectionSliceDefaultPrimary {
  /**
   * Title field in *InfoSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *InfoSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * BlurbOneTitle field in *InfoSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.primary.blurb_one_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  blurb_one_title: prismic.KeyTextField;

  /**
   * BlurbOneSubtitle field in *InfoSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.primary.blurb_one_subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  blurb_one_subtitle: prismic.KeyTextField;

  /**
   * BlurbTwoTitle field in *InfoSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.primary.blurb_two_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  blurb_two_title: prismic.KeyTextField;

  /**
   * BlurbTwoSubtitle field in *InfoSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.primary.blurb_two_subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  blurb_two_subtitle: prismic.KeyTextField;

  /**
   * BlurbThreeTitle field in *InfoSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.primary.blurb_three_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  blurb_three_title: prismic.KeyTextField;

  /**
   * BlurbThreeSubtitle field in *InfoSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.primary.blurb_three_subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  blurb_three_subtitle: prismic.KeyTextField;
}

/**
 * Default variation for InfoSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InfoSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InfoSection*
 */
type InfoSectionSliceVariation = InfoSectionSliceDefault;

/**
 * InfoSection Shared Slice
 *
 * - **API ID**: `info_section`
 * - **Description**: InfoSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoSectionSlice = prismic.SharedSlice<
  "info_section",
  InfoSectionSliceVariation
>;

/**
 * Primary content in *Spacer → Primary*
 */
export interface SpacerSliceDefaultPrimary {
  /**
   * Spacer field in *Spacer → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: spacer.primary.spacer
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  spacer: prismic.BooleanField;
}

/**
 * Default variation for Spacer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpacerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SpacerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Spacer*
 */
type SpacerSliceVariation = SpacerSliceDefault;

/**
 * Spacer Shared Slice
 *
 * - **API ID**: `spacer`
 * - **Description**: Spacer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpacerSlice = prismic.SharedSlice<"spacer", SpacerSliceVariation>;

/**
 * Primary content in *Subheader → Primary*
 */
export interface SubheaderSliceDefaultPrimary {
  /**
   * Title field in *Subheader → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subheader.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Subheader → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subheader.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Default variation for Subheader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubheaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SubheaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Subheader*
 */
type SubheaderSliceVariation = SubheaderSliceDefault;

/**
 * Subheader Shared Slice
 *
 * - **API ID**: `subheader`
 * - **Description**: Subheader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubheaderSlice = prismic.SharedSlice<
  "subheader",
  SubheaderSliceVariation
>;

/**
 * Primary content in *Text → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Text field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Rich text with formatting
   * - **API ID Path**: text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AuthorDocument,
      AuthorDocumentData,
      LandingPageDocument,
      LandingPageDocumentData,
      PostDocument,
      PostDocumentData,
      AllDocumentTypes,
      CtaSectionSlice,
      CtaSectionSliceVariation,
      CtaSectionSliceDefault,
      FaqSlice,
      FaqSliceVariation,
      FaqSliceDefault,
      HeaderSlice,
      HeaderSliceVariation,
      HeaderSliceDefault,
      HowItWorksSlice,
      HowItWorksSliceVariation,
      HowItWorksSliceDefault,
      ImageSlice,
      ImageSliceVariation,
      ImageSliceDefault,
      InfoSectionSlice,
      InfoSectionSliceVariation,
      InfoSectionSliceDefault,
      SpacerSlice,
      SpacerSliceVariation,
      SpacerSliceDefault,
      SubheaderSlice,
      SubheaderSliceVariation,
      SubheaderSliceDefault,
      TextSlice,
      TextSliceVariation,
      TextSliceDefault,
    };
  }
}
