// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Author documents
 */
interface AuthorDocumentData {
	/**
	 * Name field in *Author*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Name of the author
	 * - **API ID Path**: author.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	name: prismic.TitleField;
	
	/**
	 * Picture field in *Author*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: author.picture
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	picture: prismic.ImageField<never>;
}

/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<AuthorDocumentData>, "author", Lang>;

/**
 * Content for FAQ documents
 */
interface FaqDocumentData {
	/**
	 * Question field in *FAQ*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq.question
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	question: prismic.KeyTextField;
	
	/**
	 * Answer field in *FAQ*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq.answer
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	answer: prismic.KeyTextField;
}

/**
 * FAQ document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<FaqDocumentData>, "faq", Lang>;

type FormDocumentDataSlicesSlice = never

/**
 * Content for Form documents
 */
interface FormDocumentData {
	/**
	 * Slice Zone field in *Form*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<FormDocumentDataSlicesSlice>;/**
	 * Meta Description field in *Form*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: form.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Meta Image field in *Form*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
	
	/**
	 * Meta Title field in *Form*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: form.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * Form document from Prismic
 *
 * - **API ID**: `form`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FormDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<FormDocumentData>, "form", Lang>;

type LandingPageDocumentDataSlicesSlice = HeaderSlice | SubheaderSlice | SpacerSlice | CtaSectionSlice | InfoSectionSlice | HowItWorksSlice | TreatmentsSlice | ReviewsSlice | PricingSlice | FaqsSlice

/**
 * Content for Landing Page documents
 */
interface LandingPageDocumentData {
	/**
	 * Page Title field in *Landing Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_page.page_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	page_title: prismic.KeyTextField;
	
	/**
	 * Slice Zone field in *Landing Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice>;/**
	 * Meta Description field in *Landing Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: landing_page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Meta Image field in *Landing Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
	
	/**
	 * Meta Title field in *Landing Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: landing_page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<LandingPageDocumentData>, "landing_page", Lang>;

type PostDocumentDataSlicesSlice = TextSlice | ImageSlice

/**
 * Content for Post documents
 */
interface PostDocumentData {
	/**
	 * Product name field in *Post*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Name of the product
	 * - **API ID Path**: post.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	name: prismic.TitleField;
	
	/**
	 * Description field in *Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Description of the product
	 * - **API ID Path**: post.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * Date field in *Post*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: Date of publication
	 * - **API ID Path**: post.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	date: prismic.DateField;
	
	/**
	 * Author field in *Post*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: post.author
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	author: prismic.ContentRelationshipField<"author">;
	
	/**
	 * Cover Image field in *Post*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: post.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Price field in *Post*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: Price in USD
	 * - **API ID Path**: post.price
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	price: prismic.NumberField;
	
	/**
	 * Slice Zone field in *Post*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: post.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PostDocumentDataSlicesSlice>;
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PostDocumentData>, "post", Lang>;

/**
 * Content for Review documents
 */
interface ReviewDocumentData {
	/**
	 * Name field in *Review*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: review.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Text field in *Review*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: review.text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text: prismic.KeyTextField;
	
	/**
	 * Rating field in *Review*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: review.rating
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	rating: prismic.SelectField<"1" | "2" | "3" | "4" | "5">;
}

/**
 * Review document from Prismic
 *
 * - **API ID**: `review`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReviewDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ReviewDocumentData>, "review", Lang>;

/**
 * Content for Treatment documents
 */
interface TreatmentDocumentData {
	/**
	 * Title field in *Treatment*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: treatment.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Available field in *Treatment*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: treatment.available
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	available: prismic.BooleanField;
	
	/**
	 * Image field in *Treatment*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: treatment.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Treatment document from Prismic
 *
 * - **API ID**: `treatment`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TreatmentDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<TreatmentDocumentData>, "treatment", Lang>;

export type AllDocumentTypes = AuthorDocument | FaqDocument | FormDocument | LandingPageDocument | PostDocument | ReviewDocument | TreatmentDocument;

/**
 * Primary content in *CtaSection → Primary*
 */
export interface CtaSectionSliceDefaultPrimary {
	/**
	 * Heading field in *CtaSection → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_section.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField;
	
	/**
	 * Subheading field in *CtaSection → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_section.primary.subheading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subheading: prismic.KeyTextField;
	
	/**
	 * CTA button text field in *CtaSection → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_section.primary.cta_button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_button_text: prismic.KeyTextField;
	
	/**
	 * Image field in *CtaSection → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_section.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Mobile Image field in *CtaSection → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_section.primary.mobile_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	mobile_image: prismic.ImageField<never>;
	
	/**
	 * Type field in *CtaSection → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_section.primary.type
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	type: prismic.SelectField<"Small" | "Medium" | "Large" | "withInfoRight" | "withInfoLeft">;
	
	/**
	 * IntroText field in *CtaSection → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Only for info slices
	 * - **API ID Path**: cta_section.primary.introtext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	introtext: prismic.KeyTextField;
	
	/**
	 * Info Title One field in *CtaSection → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_section.primary.info_title_one
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	info_title_one: prismic.KeyTextField;
	
	/**
	 * Info Subtitle One field in *CtaSection → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_section.primary.info_subtitle_one
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	info_subtitle_one: prismic.KeyTextField;
	
	/**
	 * Info Title Two field in *CtaSection → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_section.primary.info_title_two
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	info_title_two: prismic.KeyTextField;
	
	/**
	 * Info Subtitle Two field in *CtaSection → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_section.primary.info_subtitle_two
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	info_subtitle_two: prismic.KeyTextField;
	
	/**
	 * Info Title Three field in *CtaSection → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_section.primary.info_title_three
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	info_title_three: prismic.KeyTextField;
	
	/**
	 * Info Subtitle Three field in *CtaSection → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_section.primary.info_subtitle_three
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	info_subtitle_three: prismic.KeyTextField;
}

/**
 * Default variation for CtaSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSectionSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CtaSectionSliceDefaultPrimary>, never>;

/**
 * Slice variation for *CtaSection*
 */
type CtaSectionSliceVariation = CtaSectionSliceDefault

/**
 * CtaSection Shared Slice
 *
 * - **API ID**: `cta_section`
 * - **Description**: CtaSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSectionSlice = prismic.SharedSlice<"cta_section", CtaSectionSliceVariation>;

/**
 * Primary content in *Faqs → Items*
 */
export interface FaqsSliceDefaultItem {
	/**
	 * Faq field in *Faqs → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faqs.items[].faq
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	faq: prismic.ContentRelationshipField<"faq">;
}

/**
 * Default variation for Faqs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<FaqsSliceDefaultItem>>;

/**
 * Slice variation for *Faqs*
 */
type FaqsSliceVariation = FaqsSliceDefault

/**
 * Faqs Shared Slice
 *
 * - **API ID**: `faqs`
 * - **Description**: Faqs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSlice = prismic.SharedSlice<"faqs", FaqsSliceVariation>;

/**
 * Primary content in *Header → Primary*
 */
export interface HeaderSliceDefaultPrimary {
	/**
	 * Title field in *Header → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Subtitle field in *Header → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
	
	/**
	 * CTA button text field in *Header → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.primary.cta_button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_button_text: prismic.KeyTextField;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<"default", Simplify<HeaderSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Primary content in *HowItWorks → Primary*
 */
export interface HowItWorksSliceDefaultPrimary {
	/**
	 * Step One Title field in *HowItWorks → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: how_it_works.primary.step_one_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	step_one_title: prismic.KeyTextField;
	
	/**
	 * Step One Text field in *HowItWorks → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: how_it_works.primary.step_one_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	step_one_text: prismic.KeyTextField;
	
	/**
	 * Step Two Title field in *HowItWorks → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: how_it_works.primary.step_two_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	step_two_title: prismic.KeyTextField;
	
	/**
	 * Step Two Text field in *HowItWorks → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: how_it_works.primary.step_two_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	step_two_text: prismic.KeyTextField;
	
	/**
	 * Step Three Title field in *HowItWorks → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: how_it_works.primary.step_three_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	step_three_title: prismic.KeyTextField;
	
	/**
	 * Step Three Text field in *HowItWorks → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: how_it_works.primary.step_three_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	step_three_text: prismic.KeyTextField;
}

/**
 * Default variation for HowItWorks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HowItWorksSliceDefault = prismic.SharedSliceVariation<"default", Simplify<HowItWorksSliceDefaultPrimary>, never>;

/**
 * Slice variation for *HowItWorks*
 */
type HowItWorksSliceVariation = HowItWorksSliceDefault

/**
 * HowItWorks Shared Slice
 *
 * - **API ID**: `how_it_works`
 * - **Description**: HowItWorks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HowItWorksSlice = prismic.SharedSlice<"how_it_works", HowItWorksSliceVariation>;

/**
 * Primary content in *Image → Primary*
 */
export interface ImageSliceDefaultPrimary {
	/**
	 * Image field in *Image → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ImageSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *InfoSection → Primary*
 */
export interface InfoSectionSliceDefaultPrimary {
	/**
	 * Title field in *InfoSection → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: info_section.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Subtitle field in *InfoSection → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: info_section.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
	
	/**
	 * BlurbOneTitle field in *InfoSection → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: info_section.primary.blurb_one_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	blurb_one_title: prismic.KeyTextField;
	
	/**
	 * BlurbOneSubtitle field in *InfoSection → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: info_section.primary.blurb_one_subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	blurb_one_subtitle: prismic.KeyTextField;
	
	/**
	 * BlurbTwoTitle field in *InfoSection → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: info_section.primary.blurb_two_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	blurb_two_title: prismic.KeyTextField;
	
	/**
	 * BlurbTwoSubtitle field in *InfoSection → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: info_section.primary.blurb_two_subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	blurb_two_subtitle: prismic.KeyTextField;
	
	/**
	 * BlurbThreeTitle field in *InfoSection → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: info_section.primary.blurb_three_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	blurb_three_title: prismic.KeyTextField;
	
	/**
	 * BlurbThreeSubtitle field in *InfoSection → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: info_section.primary.blurb_three_subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	blurb_three_subtitle: prismic.KeyTextField;
}

/**
 * Default variation for InfoSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoSectionSliceDefault = prismic.SharedSliceVariation<"default", Simplify<InfoSectionSliceDefaultPrimary>, never>;

/**
 * Slice variation for *InfoSection*
 */
type InfoSectionSliceVariation = InfoSectionSliceDefault

/**
 * InfoSection Shared Slice
 *
 * - **API ID**: `info_section`
 * - **Description**: InfoSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoSectionSlice = prismic.SharedSlice<"info_section", InfoSectionSliceVariation>;

/**
 * Primary content in *Pricing → Primary*
 */
export interface PricingSliceDefaultPrimary {
	/**
	 * Title field in *Pricing → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pricing.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Subtitle field in *Pricing → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pricing.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
	
	/**
	 * Description field in *Pricing → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pricing.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * Bullet One field in *Pricing → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pricing.primary.bullet_one
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	bullet_one: prismic.KeyTextField;
	
	/**
	 * Bullet Two field in *Pricing → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pricing.primary.bullet_two
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	bullet_two: prismic.KeyTextField;
	
	/**
	 * Bullet Three field in *Pricing → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pricing.primary.bullet_three
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	bullet_three: prismic.KeyTextField;
}

/**
 * Default variation for Pricing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingSliceDefault = prismic.SharedSliceVariation<"default", Simplify<PricingSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Pricing*
 */
type PricingSliceVariation = PricingSliceDefault

/**
 * Pricing Shared Slice
 *
 * - **API ID**: `pricing`
 * - **Description**: Pricing
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingSlice = prismic.SharedSlice<"pricing", PricingSliceVariation>;

/**
 * Primary content in *Reviews → Items*
 */
export interface ReviewsSliceDefaultItem {
	/**
	 * Review field in *Reviews → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: reviews.items[].review
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	review: prismic.ContentRelationshipField<"review">;
}

/**
 * Default variation for Reviews Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsSliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<ReviewsSliceDefaultItem>>;

/**
 * Slice variation for *Reviews*
 */
type ReviewsSliceVariation = ReviewsSliceDefault

/**
 * Reviews Shared Slice
 *
 * - **API ID**: `reviews`
 * - **Description**: Reviews
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsSlice = prismic.SharedSlice<"reviews", ReviewsSliceVariation>;

/**
 * Primary content in *Spacer → Primary*
 */
export interface SpacerSliceDefaultPrimary {
	/**
	 * Spacer field in *Spacer → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: spacer.primary.spacer
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	spacer: prismic.BooleanField;
}

/**
 * Default variation for Spacer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpacerSliceDefault = prismic.SharedSliceVariation<"default", Simplify<SpacerSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Spacer*
 */
type SpacerSliceVariation = SpacerSliceDefault

/**
 * Spacer Shared Slice
 *
 * - **API ID**: `spacer`
 * - **Description**: Spacer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpacerSlice = prismic.SharedSlice<"spacer", SpacerSliceVariation>;

/**
 * Primary content in *Subheader → Primary*
 */
export interface SubheaderSliceDefaultPrimary {
	/**
	 * Title field in *Subheader → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: subheader.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Subtitle field in *Subheader → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: subheader.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Default variation for Subheader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubheaderSliceDefault = prismic.SharedSliceVariation<"default", Simplify<SubheaderSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Subheader*
 */
type SubheaderSliceVariation = SubheaderSliceDefault

/**
 * Subheader Shared Slice
 *
 * - **API ID**: `subheader`
 * - **Description**: Subheader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubheaderSlice = prismic.SharedSlice<"subheader", SubheaderSliceVariation>;

/**
 * Primary content in *Text → Primary*
 */
export interface TextSliceDefaultPrimary {
	/**
	 * Text field in *Text → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Rich text with formatting
	 * - **API ID Path**: text.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<"default", Simplify<TextSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

/**
 * Primary content in *Treatments → Items*
 */
export interface TreatmentsSliceDefaultItem {
	/**
	 * Treatment field in *Treatments → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: treatments.items[].treatment
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	treatment: prismic.ContentRelationshipField<"treatment">;
}

/**
 * Default variation for Treatments Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TreatmentsSliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<TreatmentsSliceDefaultItem>>;

/**
 * Slice variation for *Treatments*
 */
type TreatmentsSliceVariation = TreatmentsSliceDefault

/**
 * Treatments Shared Slice
 *
 * - **API ID**: `treatments`
 * - **Description**: Treatments
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TreatmentsSlice = prismic.SharedSlice<"treatments", TreatmentsSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			AuthorDocument,
			AuthorDocumentData,
			FaqDocument,
			FaqDocumentData,
			FormDocument,
			FormDocumentData,
			FormDocumentDataSlicesSlice,
			LandingPageDocument,
			LandingPageDocumentData,
			LandingPageDocumentDataSlicesSlice,
			PostDocument,
			PostDocumentData,
			PostDocumentDataSlicesSlice,
			ReviewDocument,
			ReviewDocumentData,
			TreatmentDocument,
			TreatmentDocumentData,
			AllDocumentTypes,
			CtaSectionSlice,
			CtaSectionSliceDefaultPrimary,
			CtaSectionSliceVariation,
			CtaSectionSliceDefault,
			FaqsSlice,
			FaqsSliceDefaultItem,
			FaqsSliceVariation,
			FaqsSliceDefault,
			HeaderSlice,
			HeaderSliceDefaultPrimary,
			HeaderSliceVariation,
			HeaderSliceDefault,
			HowItWorksSlice,
			HowItWorksSliceDefaultPrimary,
			HowItWorksSliceVariation,
			HowItWorksSliceDefault,
			ImageSlice,
			ImageSliceDefaultPrimary,
			ImageSliceVariation,
			ImageSliceDefault,
			InfoSectionSlice,
			InfoSectionSliceDefaultPrimary,
			InfoSectionSliceVariation,
			InfoSectionSliceDefault,
			PricingSlice,
			PricingSliceDefaultPrimary,
			PricingSliceVariation,
			PricingSliceDefault,
			ReviewsSlice,
			ReviewsSliceDefaultItem,
			ReviewsSliceVariation,
			ReviewsSliceDefault,
			SpacerSlice,
			SpacerSliceDefaultPrimary,
			SpacerSliceVariation,
			SpacerSliceDefault,
			SubheaderSlice,
			SubheaderSliceDefaultPrimary,
			SubheaderSliceVariation,
			SubheaderSliceDefault,
			TextSlice,
			TextSliceDefaultPrimary,
			TextSliceVariation,
			TextSliceDefault,
			TreatmentsSlice,
			TreatmentsSliceDefaultItem,
			TreatmentsSliceVariation,
			TreatmentsSliceDefault
		}
	}
}