// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
	cta_section: dynamic(() => import('./CtaSection')),
	faqs: dynamic(() => import('./Faqs')),
	header: dynamic(() => import('./Header')),
	how_it_works: dynamic(() => import('./HowItWorks')),
	image: dynamic(() => import('./Image')),
	info_section: dynamic(() => import('./InfoSection')),
	pricing: dynamic(() => import('./Pricing')),
	reviews: dynamic(() => import('./Reviews')),
	spacer: dynamic(() => import('./Spacer')),
	subheader: dynamic(() => import('./Subheader')),
	text: dynamic(() => import('./Text')),
	treatments: dynamic(() => import('./Treatments'))
}
