// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cta_section: dynamic(() => import("./CtaSection")),
  faq: dynamic(() => import("./Faq")),
  header: dynamic(() => import("./Header")),
  how_it_works: dynamic(() => import("./HowItWorks")),
  image: dynamic(() => import("./Image")),
  info_section: dynamic(() => import("./InfoSection")),
  spacer: dynamic(() => import("./Spacer")),
  subheader: dynamic(() => import("./Subheader")),
  text: dynamic(() => import("./Text")),
};
