// This file is generated by Slice Machine. Update with care!

import Image from './Image'
import Text from './Text'
import Header from './Header'
import Subheader from './Subheader'
import Faq from './Faq'
import Spacer from './Spacer'

export { Image, Text, Header, Subheader, Faq }

export const components = {
  image: Image,
  text: Text,
  header: Header,
  subheader: Subheader,
  faq: Faq,
  spacer: Spacer
}
