export const fieldMap = {
  first_name: 1,
  last_name: 1,
  gender: 2,
  birthdate: 3,
  country: 4,
  phone_number: 5,
  notice_hair_loss: 6,
  medications: 7,
  conditions: 8,
  questions: 9,
  stage: 10,
  product: 11,
  shipping_address: 13,
  profile_image_url: 14,
  photo_id_url: 15,
  has_health_card: 16,
  has_insurance: 17,
  billing_address: 18,
};
